export const corsi = [
    "Architettura",
    "Assistenza Sanitaria",
    "Biotecnologie Mediche e Diagnostiche",
    "Chimica",
    "Chimica e Tecnologia Farmaceutiche",
    "Computer Engineering",
    "Comunicazione Interlinguistica Applicata",
    "Comunicazione Interlinguistica Applicata alle Professioni Giuridiche",
    "Disegno Industriale",
    "Filosofia",
    "Ingegneria Civile e Ambientale",
    "Ingegneria dell'Informazione",
    "Ingegneria Industriale",
    "Lettere",
    "Lingue e Culture Moderne",
    "Medicina e Chirurgia",
    "Medicina Veterinaria",
    "Odontoiatria e Protesi Dentaria",
    "Professioni Sanitarie della Prevenzione",
    "Professioni Sanitarie della Riabilitazione",
    "Professioni Sanitarie, Infermieristiche e Professione Sanitaria Ostetrica",
    "Professioni Sanitarie Tecniche",
    "Scienze Biologiche",
    "Scienze dei Beni Culturali",
    "Scienze dei Servizi Giuridici",
    "Scienze del Servizio Sociale",
    "Scienze del Turismo",
    "Scienze della Comunicazione",
    "Scienze della Difesa e della Sicurezza",
    "Scienze della Mediazione Linguistica",
    "Scienze della Terra",
    "Scienze dell'Amministrazione",
    "Scienze dell'Architettura e dell'Ingegneria Edile",
    "Scienze delle Attività Motorie e Sportive",
    "Scienze dell'Economia e della Gestione Aziendale",
    "Scienze dell'Educazione e della Formazione",
    "Scienze e Tecniche Psicologiche",
    "Scienze e Tecnologie Agrarie, Agroalimentari e Forestali",
    "Scienze e Tecnologie Chimiche",
    "Scienze e Tecnologie della Navigazione Marittima e Aerea",
    "Scienze e Tecnologie delle Arti Figurative, della Musica, dello Spettacolo e della Moda",
    "Scienze e Tecnologie Farmaceutiche",
    "Scienze e Tecnologie Fisiche",
    "Scienze e Tecnologie Informatiche",
    "Scienze e Tecnologie per l'Ambiente e la Natura",
    "Scienze e Tecnologie Zootecniche e delle Produzioni Animali",
    "Scienze Economiche",
    "Scienze Geografiche",
    "Scienze Giuridiche",
    "Scienze Matematiche",
    "Scienze Politiche e delle Relazioni Internazionali",
    "Scienze Sociali per la Cooperazione, lo Sviluppo e la Pace",
    "Scienze Sociologiche",
    "Scienze Statistiche",
    "Scienze Storiche",
    "Tecnologie per la Conservazione e il Restauro dei Beni Culturali",
    "Urbanistica e Scienze della Pianificazione Territoriale e Ambientale"
];