export const universita = [
    "Università degli Studi di Bari",
    "Politecnico di Bari",
    "Libera Università Mediterranea Jean Monnet di Casamassima (LUM)",
    "Università del Sannio di Benevento",
    "Università degli Studi Giustino Fortunato",
    "Università degli Studi di Bergamo",
    "Alma Mater Studiorum - Università di Bologna",
    "Libera Università di Bolzano/Freie Universität Bozen",
    "Università degli Studi di Brescia",
    "Università degli Studi di Cagliari",
    "Università di Camerino",
    "Università degli Studi del Molise",
    "Università degli Studi di Cassino",
    "Libera Università \"Carlo Cattaneo\" - LIUC",
    "Università degli Studi di Catania",
    "Università degli Studi \"Magna Graecia\" di Catanzaro",
    "Università degli Studi \"Gabriele D'Annunzio\" di Chieti-Pescara",
    "Università Kore di Enna",
    "Istituto Superiore per le Industrie Artistiche - ISIA di Faenza",
    "Università degli Studi di Ferrara",
    "Università degli Studi di Firenze",
    "SUM - Istituto Italiano di Scienze Umane di Firenze",
    "Università degli Studi di Foggia",
    "Università degli Studi di Genova",
    "Università degli Studi dell'Aquila",
    "Università degli Studi del Salento",
    "Scuola IMT - Istituzioni, Mercati, Tecnologie - Alti Studi - Lucca",
    "Università degli Studi di Macerata",
    "Università degli Studi di Messina",
    "Università degli Studi di Milano",
    "Università degli Studi di Milano-Bicocca",
    "Politecnico di Milano",
    "Università Cattolica del Sacro Cuore",
    "Università Commerciale Luigi Bocconi",
    "Libera Università di lingue e comunicazione IULM",
    "Libera Università \"Vita Salute San Raffaele\" Milano",
    "Università degli Studi di Modena e Reggio Emilia",
    "Università degli Studi di Napoli \"Federico II\"",
    "Università degli Studi della Campania Luigi Vanvitelli",
    "Università degli Studi di Napoli \"Parthenope\"",
    "Università degli Studi di Napoli \"L\'Orientale\"",
    "Università degli Studi Suor Orsola Benincasa - Napoli",
    "Università degli Studi Pegaso",
    "Università degli Studi di Padova",
    "Università degli Studi di Palermo",
    "Università degli Studi di Parma",
    "Università degli Studi di Pavia",
    "Università degli Studi di Perugia",
    "Università per Stranieri di Perugia",
    "Università degli Studi di Pisa",
    "Scuola Superiore di Studi Universitari e di Perfezionamento Sant'Anna di Pisa",
    "Scuola Normale Superiore di Pisa",
    "Università degli Studi della Basilicata",
    "Università degli Studi \"Mediterranea\" di Reggio Calabria",
    "Università per Stranieri \"Dante Alighieri\" di Reggio Calabria",
    "Università della Calabria",
    "Sapienza Università di Roma",
    "Università degli Studi di Roma \"Tor Vergata\"",
    "Università degli Studi di Roma Tre",
    "Istituto Superiore per le Industrie Artistiche - ISIA di Roma",
    "Libera Università Internazionale Studi Sociali \"Guido Carli\" LUISS-ROMA",
    "Libera Università \"Maria SS. Assunta\" (LUMSA)",
    "Università \"Campus Bio-medico\" di Roma",
    "Università Europea di Roma",
    "Università degli Studi Internazionali di Roma",
    "Università degli Studi Link Campus University",
    "Università degli Studi Niccolò Cusano",
    "Università degli Studi Guglielmo Marconi",
    "Università degli Studi di Salerno",
    "Università degli Studi di Sassari",
    "Università degli Studi di Siena",
    "Università per Stranieri di Siena",
    "Università degli Studi di Teramo",
    "Università degli Studi di Trento",
    "Università degli Studi di Trieste",
    "Scuola Superiore di Studi Avanzati di Trieste",
    "Università degli Studi di Torino",
    "Politecnico di Torino",
    "Università degli Studi dell'Insubria",
    "Istituto Universitario di Studi Superiori di Pavia",
    "Università degli Studi di Urbino \"Carlo Bo\"",
    "Istituto Superiore per le Industrie Artistiche - ISIA di Urbino",
    "Università degli Studi della Valle D'Aosta",
    "Università degli Studi di Venezia \"Ca\' Foscari\"",
    "Università Iuav di Venezia",
    "Università degli Studi di Verona"
]
